usuarios:
  - codigo: 20241001
    contrasenia: a123
    mac: fa:16:3e:28:2e:98
    ip: 10.0.0.1
    port: 5811
    usuario_h1: ubuntu
    contra_h1: Pablox12344
    nombre: Carlos Gomez
    rol: Estudiante
  - codigo: 20001002
    contrasenia: a123
    mac: fa:16:3e:28:2e:98
    ip: 10.0.0.1
    port: 5811
    usuario_h1: ubuntu
    contra_h1: Pablox12344
    nombre: Ana Rivera
    rol: Profesor
  - codigo: 20241003
    contrasenia: a123
    mac: fa:16:3e:28:2e:98
    ip: 10.0.0.1
    port: 5811
    usuario_h1: ubuntu
    contra_h1: Pablox12344
    nombre: Juan Martinez
    rol: Estudiante
  - codigo: 20051003
    contrasenia: a123
    mac: fa:16:3e:28:2e:98
    ip: 10.0.0.1
    port: 5811
    usuario_h1: ubuntu
    contra_h1: Pablox12344
    nombre: Armando Casas
    rol: Administrador
  - codigo: 20031212
    contrasenia: a123
    mac: fa:16:3e:28:2e:98
    ip: 10.0.0.1
    port: 5811
    usuario_h1: ubuntu
    contra_h1: Pablox12344
    nombre: Manuel Yarleque
    rol: Profesor
cursos:
  - alumnos:
      - 20241001
      - 20241003
    codigo_curso: TEL201
    nombre: Redes Definidas por Software
    profesor: 20001002
    servidor:
      - codigo_servidor: ServerTEL1
        servicios_permitidos:
          - ssh
          - web
  - alumnos:
      - 20241003
    codigo_curso: TEL202
    nombre: Introducción a Bases de Datos
    profesor: 20031212
    servidor:
      - codigo_servidor: ServerTEL2
        servicios_permitidos:
          - ssh
servidores:
  - codigo_servidor: ServerTEL1
    ip: 10.0.0.2
    mac: fa:16:3e:e7:63:77
    nombre: Servidor 1
    protocolo_conexion: TCP
    puerto: 22
    servicio: ssh
  - codigo_servidor: ServerTEL2
    ip: 10.0.0.3
    mac: fa:16:3e:d4:cb:2f
    nombre: Servidor 2
    protocolo_conexion: TCP
    puerto: 22
    servicio: ssh
notas:
  - alumnos:
      - alumno: 20241001
        ex1: Pendiente
        ex2: Pendiente
        pc1: 13
        pc2: 12
        pc3: 15
        pc4: 13
      - alumno: 20241003
        ex1: Pendiente
        ex2: Pendiente
        pc1: 16
        pc2: 14
        pc3: 17
        pc4: 18
    curso: TEL201
    nombre: Redes Definidas por Software
  - alumnos:
      - alumno: 20241003
        ex1: 12
        ex2: Pendiente
        lab1: 16
        lab2: 15
        lab3: 14
        lab4: 18
        lab5: Pendiente
        lab6: Pendiente
        lab7: Pendiente
      - alumno: 20241001
        ex1: Pendiente
        ex2: Pendiente
        lab1: Pendiente
        lab2: Pendiente
        lab3: Pendiente
        lab4: Pendiente
        lab5: Pendiente
        lab6: Pendiente
        lab7: Pendiente
    curso: TEL202
    nombre: Introducción a Bases de Datos